// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4jyEuJyx7MaMJ0w6v9xVwwuhMvrZLnI',
    appId: '1:556608328768:web:171eba986ed045efc63ba5',
    messagingSenderId: '556608328768',
    projectId: 'social-media-yp',
    authDomain: 'social-media-yp.firebaseapp.com',
    storageBucket: 'social-media-yp.appspot.com',
    measurementId: 'G-Z2YW0QBLVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_xZktdx4TILP9Ajf3Hvd_DRTBckD-20',
    appId: '1:556608328768:android:b4d7287ab3d9c155c63ba5',
    messagingSenderId: '556608328768',
    projectId: 'social-media-yp',
    storageBucket: 'social-media-yp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjnETmv7ZrLVgxmqyhoPf23kr0D00Utw',
    appId: '1:556608328768:ios:5a1b8cc82dfc6977c63ba5',
    messagingSenderId: '556608328768',
    projectId: 'social-media-yp',
    storageBucket: 'social-media-yp.appspot.com',
    androidClientId:
        '556608328768-orgercq1oils2ishflb159fe1uv59ckb.apps.googleusercontent.com',
    iosClientId:
        '556608328768-3tvmgd9ierg30otcvubqku89p0l3ltc0.apps.googleusercontent.com',
    iosBundleId: 'com.youapps.socialMedia',
  );
}
